247 membership state
juntagrico/juntagrico pull request #254
Opened 2020-08-23 18:27 UTC by motu55

do not merge before #244 since it contains these commits

2020-11-08 12:32 UTC, pascalfree requested changes
checking this, I found that the member cancellation form needs to be updated. Will make a separate pull request for that.

2020-11-08 12:32 UTC, pascalfree commented on juntagrico/dao/memberdao.py
>          return Member.objects.filter(subscriptionmembership__subscription__activation_date__isnull=False).exclude(
We may want to check here, that the member hasn't left the subscription.

2020-11-08 12:32 UTC, pascalfree commented on juntagrico/entity/member.py
>          _('Enddatum'), null=True, blank=True)
add a help text, to clarify what this field means in comparison to the deactivation date.

2020-11-08 21:31 UTC, pascalfree commented on juntagrico/dao/memberdao.py
> +        return Member.objects.filter(MemberDao.has_subscription).exclude(
`MemberDao.has_subscription` should check that member has not left the given subscription. It should also be aware of future dates. That's actually a bug from another feature.

2020-11-11 19:49 UTC, motu55 commented
i removed the restrictions since we have the correspondings checks

2020-11-11 20:30 UTC, pascalfree approved these changes

2020-11-11 20:35 UTC, merged