#302 Prevent new extras and parts for canceled subscriptions
juntagrico/juntagrico pull request #304
Opened 2020-10-26 21:22 UTC by nixnuex

Close #302

2020-10-27 08:47 UTC, motu55 requested changes
all in all ok
also it seems that this pullrequest revertes this 
https://github.com/juntagrico/juntagrico/pull/292/files
the zusatzabo naming

2020-10-27 08:47 UTC, motu55 commented on juntagrico/views_subscription.py
> +    if request.method == 'POST' and parts_order_allowed:
throw an exception when someone orders a part in a cancelled subscription

2020-10-27 08:47 UTC, motu55 commented on juntagrico/views_subscription.py
> +    if request.method == 'POST' and extra_order_allowed:
same here

2020-10-27 10:40 UTC, nixnuex commented
True. I found more occurances of "Zusatzabo" than "Zusatz-Abo". Thats why. Will clean up the rest in a separate pull request.

2020-10-28 20:33 UTC, motu55 approved these changes

2020-10-28 20:34 UTC, merged