#536 Add config for membership cancellation notice period
juntagrico/juntagrico pull request #537
Opened 2022-03-31 20:50 UTC by nixnuex

Closes #536

2022-04-09 09:34 UTC, nixnuex commented
Also closes #538

2022-04-09 13:59 UTC, pascalfree requested changes

2022-04-09 13:59 UTC, pascalfree commented on juntagrico/templates/manage_shares.html
> +                                       onclick="return confirm('{% blocktrans %} Möchtest du sicher diese/s/n {{ v_share }} verbindlich zum {{ canceldate }} kündigen? {% endblocktrans%}')">
Using the chance to fix the sentence
```suggestion
                                       onclick="return confirm('{% blocktrans %} Möchtest du diese/s/n {{ v_share }} verbindlich zum {{ canceldate }} kündigen? {% endblocktrans%}')">
```

2022-04-09 13:59 UTC, pascalfree commented on juntagrico/views_subscription.py
> +        'canceldate': next_membership_end_date(),
call it 'next_membership_end_date'.

2022-04-09 13:59 UTC, pascalfree commented on juntagrico/templates/manage_shares.html
> +                                    {% blocktrans %}Kann gekündigt werden, sobald eine IBAN hinterlegt ist{% endblocktrans %}
Add a link here to the form where the IBAN can be set.

2022-10-09 15:27 UTC, pascalfree approved these changes

2022-10-09 15:58 UTC, merged